#!/usr/bin/env ruby

require 'optparse'


class msgtranslate

    def initialize()

    end

end



# ============================================================================


if $0 == __FILE__

options = {}

OptionParser.new { |opts|
    opts.banner = "Usage: msgtranslat FROM TO [OPTION] INPUTFILE"   
}.parse!

end
